name: Cloud doc tests

on:
  workflow_dispatch: # Allows manual trigger of the workflow
  repository_dispatch: # Allows other repositories to trigger this workflow
    types: [run-cloud-doc-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create .env file
      run: |
        echo PASSWORD=${{ secrets.CLOUD_PASSWORD }} > tests/.env
      shell: bash

    - name: Install dependencies and run tests
      id: test_script
      run: |
        npm install
        node ./node_modules/doc-detective-core/scripts/postinstall.js
        OUTPUT=$(npm run test-cloud-docs --silent)
        echo "test_output=$OUTPUT" >> $GITHUB_ENV

    - name: Check for failed tests and create GitHub issue
      if: contains(env.test_output, 'FAIL')
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issueBody = `Failed Tests Output: \n\`\`\`\n${process.env.test_output}\n\`\`\``;
          const issueTitle = 'Failed Cloud Doc Tests';
          github.rest.issues.create({
            owner: 'redpanda-data',
            repo: 'documentation-private',
            title: issueTitle,
            body: issueBody
          });
