name: Cloud doc tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-cloud-doc-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        run: echo PASSWORD=${{ secrets.CLOUD_PASSWORD }} > tests/.env
        shell: bash

      - name: Install dependencies and run tests
        run: |
          npm install
          node ./node_modules/doc-detective-core/scripts/postinstall.js
          npm run test-cloud-docs --silent

      - name: Check for failed tests and save to ENV
        run: |
          if grep -q FAIL test_output.json; then
            echo "failed_tests=true" >> $GITHUB_ENV
          else
            echo "failed_tests=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue for Failed Tests
        if: env.failed_tests == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          script: |
            const fs = require('fs');
            const issueBody = fs.readFileSync('./tests/test_output.json', 'utf8');
            const issueTitle = 'Failed Cloud Doc Tests';
            github.rest.issues.create({
              owner: 'Actions-tester-jake',
              repo: 'docs',
              title: issueTitle,
              body: `Failed Tests Output:\n\`\`\`\n${issueBody}\n\`\`\``
            });
